### ISSUE TITLE
Can't correctly show return-value type

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnSpy#1040]
- What version did you use?
v6.0.0.0
- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Open mscorlib.dll (.NET 4.0)
2. Jump to "System.SZArrayHelper"
3. Hover above "JitHelpers.UnsafeCast<T[]>(this);"

![snipaste_2019-01-05_21-02-13](https://user-images.githubusercontent.com/27536652/50724938-9c4e7280-1130-11e9-929c-399ba5118194.png)

**Comment by Tianjiao** [comment]
Repro in my here. Happens also on Unsafe.As<T[]>(this) on System.Private.CoreLib.dll
![bug21](https://user-images.githubusercontent.com/1756057/50731246-c5a3e880-119a-11e9-9290-c90ef48b051d.png)

- Change dnSpy language to English doesn't work.
- Set system unicode to English(US) doesn't work.

Steps:

1. Search "SZArrayHelper"
2. Double-click .ctor of "SZArrayHelper" from System.Private.CoreLib.dll
3. Hover over Unsafe.As<T[]>(this)

**Comment by 0xd4d** [comment]
That's the same issue

**Comment by AbeniMatteo** [comment]
I thought the tooltip was showing multiple U+25A1 WHITE SQUARE chars, instead those are pairs of square brackets.

The problem is inside this [method](https://github.com/0xd4d/dnSpy/blob/39b5b369825668fa3fa54410931189877be63db0/dnSpy/dnSpy.Decompiler/CSharp/CSharpFormatter.cs#L864).
If the generic argument of the method is SZArray, the formatter keeps looping between T (MVar) and the array (SZArray) of `T[]`  until it reaches `TypeFormatterUtils.MAX_RECURSION`, printing only the square brackets of the array.

During my tests i've found that passing an empty list instead of `methGenArgs` [here](https://github.com/0xd4d/dnSpy/blob/39b5b369825668fa3fa54410931189877be63db0/dnSpy/dnSpy.Decompiler/CSharp/CSharpFormatter.cs#L887), "solves" the problem.

I don't have enough experience with this codebase to propose a fix, so i hope these notes will help you.
