### ISSUE TITLE
.XAML/.baml editing 

### ISSUE THREAD

**Issue by InochiPM** [0xd4d/dnSpy#1080]
I saw a handfull of other requests and issues on the ability to edit .XAML/.baml files in dnSpy but most of them say they have been removed from the future plans.
From what i can see it's not implemented and was dropped form this project back in December i would say?
I currently need to find a way to edit .baml files from within dnSpy, the forms are stored in xaml/baml format and i can dump the files raw as the baml or as .xaml but when i add them back in as a new resource it breaks the program.

**Comment by UlyssesWu** [comment]
Still I would say it's a dup of #171 . Maybe asking at there is better.

I have seen that you once wanted to make a CeVIO translation. But since C now has an English translation (and [other translation](https://github.com/VOICeVIO/CeVIO.CN) without BAML editing needed), I don't know what you want to do now.

**Comment by 0xd4d** [comment]
Yes it's a dupe.
