### ISSUE TITLE
Extension for CommandLine Break Point (AT)

### ISSUE THREAD

**Issue by josegomez** [0xd4d/dnSpy#1093]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
6.0.3

I am trying to write an extension to support breaking at a certain Type (Class) when attaching to a running process using command line.
I've started writing the extension following the extension guide however there isn't a lot there to go on. Can anyone point me in the right direction? What event if any can I hook onto? I am trying to make ti fairly generic but frankly if I can just write a "hack" extension to always break at class XXYZ on Attach that would work too. This is for an embedded tool and will always use the same class name

**Comment by 0xd4d** [comment]
Sorry, I forgot about this issue.

Since your code is a debugger extension, your main code should export a class that implements `IDbgManagerStartListener`. All classes that implement it get created (once) before any program is debugged. So it can be used to initialize stuff, eg. hook debugger events, set breakpoints, etc.

To set breakpoints, import the `DbgCodeBreakpointsService` class.

However it's probably easier to create .NET breakpoints by using `DbgDotNetBreakpointFactory` (import it). You'll need to get a `ModuleId`. You can either create one yourself or you can import and use an `IModuleIdProvider` to get a `ModuleId` if you have a `ModuleDef` instance. You can get a `ModuleDef` by finding the module in Assembly Explorer by importing an `IDsDocumentService` instance. Find a doc that is a `DsDotNetDocumentBase` and you can access its `ModuleDef` prop to get what you need. You can also use it to find the class and method (you'll need the method token).
