### ISSUE TITLE
Analyzer doesn't work properly when analyzing methods that are "used" by the Unity coroutines.

### ISSUE THREAD

**Issue by utf69** [0xd4d/dnSpy#1152]
**The code in the Assembly-CSharp.dll was obfuscated by the BeeBytes Obfuscator.**

Analyzer seems to think that some of the methods are "used" by the coroutines, even if they aren't even appearing in the coroutine itself.

![obraz](https://user-images.githubusercontent.com/40630642/58966597-d93b9580-87b2-11e9-84d1-3821c8c47df3.png)

When I delete the duplicated coroutine, the Used By node is showing another dummy coroutine.

![obraz](https://user-images.githubusercontent.com/40630642/58966628-eb1d3880-87b2-11e9-9e37-cfceeea50eab.png)

I used dnSpy 6.0.5 (64-bit).

Steps needed to reproduce:
1. Open Assembly-CSharp.dll
2. Go to the ImplicitLogin class (in the blank namespace).
3. Go to the IDCMDCHFJMD method.
4. Analyze it.
5. The Used By node should contain only one IEnumerator.
6. The IEnumerator should not reference the IDCMDCHFJMD.
7. Delete the IEnumerator found in the Used By node.
8. Another dummy IEnumerator will appear (or the real one - Start).

This problem also appears when I'm scanning and then removing the dummy IEnumerators with dnlib.

![obraz](https://user-images.githubusercontent.com/40630642/58967586-bf9b4d80-87b4-11e9-9c37-b7741129a530.png)

I had to pack it since it didn't let me upload just the raw .dll file.
[Assembly-CSharp.zip](https://github.com/0xd4d/dnSpy/files/3257759/Assembly-CSharp.zip)

**Comment by 0xd4d** [comment]
There's a hidden class that you can see if you enable decompiler option `Show hidden compiler generated types and methods`, it's called `AICPAKKJDJM`. One of its methods references `IDCMDCHFJMD()` so if you remove the method you'll get the errors by dnlib since it's still referenced by some code.

`AICPAKKJDJM` is an enumerator class used by `ECIHCBDIBON()` and the analyzer has some basic support for C# iterators and lambdas but it's not perfect. It checks every method of this enumerator class and assumes that if there's a method call, it's used by the iterator method (`ECIHCBDIBON()`). In this particular case it's not true, but in normal non-obfuscated code it's true.

This is not likely to be fixed so I'm closing it.

**Comment by utf69** [comment]
Oh, ok thanks very much. After changing `Module.Types` to `Module.GetTypes()` my deobfuscator actually works pretty well (~50k methods => 3k methods).
