### ISSUE TITLE
Decompiler doesn't support Roslyn compiled code

### ISSUE THREAD

**Issue by escms** [0xd4d/dnSpy#118]
![qq 20160421215728](https://cloud.githubusercontent.com/assets/7844745/14711538/3ecad0e8-080c-11e6-8323-8bb78996c4ed.png)

**Comment by escms** [comment]
On the left is JustDecompile, on the right is dnspy.
linq

**Comment by UlyssesWu** [comment]
JD actually has better result when decompiling linq, that's because JD uses their own decompilation engine while dnSpy mainly using ILSpy engine. I don't think which one is better, because JD engine sometimes may ingore something(attritubes, initialization statements, necessary namespaces etc.), makes the decompiled code more difficult to re-compile, while ILSpy engine is better in that aspect.

In fact JD engine seems to be open-sourse, too. [See here.](https://github.com/telerik/JustDecompileEngine)
If you are interested, you may make use of it to improve dnSpy.

BTW, those Chinese words makes me laugh. I suggest you process pictures before upload them.

**Comment by 0xd4d** [comment]
That's probably code compiled by Roslyn, which the decompiler doesn't handle very well at the moment. Unless the ILSpy maintainers update their decompiler, I plan to do that but it's not a priority, so don't expect it any time soon.

**Comment by rolandh** [comment]
Is it possible for us to reparse the decompiled code with a plugin? I would like to add in some string deobfusication methods without actually changing the original source.

**Comment by 0xd4d** [comment]
Reparsing decompiled code isn't recommended, just use ILanguage to decompile the code. This is off topic, if you have more questions, create a new issue.

**Comment by 0xd4d** [comment]
A lot of these problems were fixed a couple of months ago.

**Comment by vikramambrose** [comment]
Not sure if this is related but I'm running yesterday's git and noticed these symbols e.g. "d__59" which prevent me from making modifications and recompiling. What does d__59 mean?

This is a simple button click method;

```
private void OnLogin(object parameter)
{
	LoginViewModel.<OnLogin>d__59 <OnLogin>d__ = new LoginViewModel.<OnLogin>d__59();
	<OnLogin>d__.<>4__this = this;
...
}
```

**Comment by 0xd4d** [comment]
That's an async method, probably a Debug build since the state machine seems to be a reference type. Make sure async method decompilation is enabled in the settings.

**Comment by vikramambrose** [comment]
I do have "Decompile async methods" ticked under Decompiler options but it doesn't make a difference in this case.

**Comment by 0xd4d** [comment]
@vikramambrose Create a new issue and attach the assembly since it's impossible for me to know what's preventing it from being recognized as an async method.
