### ISSUE TITLE
Copy unknown Metadata streams option doesn't save the unknown stream

### ISSUE THREAD

**Issue by xsilent007** [0xd4d/dnSpy#1204]
Version used: v6.0.5

Issue: After selecting the "Copy unknown Metadata streams" option in the save file prompt, the stream does not get saved.

Before: ![before](https://i.vgy.me/VRcD3X.png)

After: ![after](https://i.vgy.me/EXUDJS.png)

[File that was tested](https://cdn.discordapp.com/attachments/559075662229405701/600369614991523840/CrackMe_KoiVm.exe)

**Comment by 0xd4d** [comment]
Attach the original file

**Comment by 0xd4d** [comment]
Probably fixed by https://github.com/0xd4d/dnlib/commit/e2e47613a0545ce24fc026fd6fa6b1326a0c4c0a , you can verify it by closing dnSpy, download the [latest dnlib build](https://ci.appveyor.com/project/0xd4d/dnlib/build/artifacts), extract the built dnlib file from the nupkg (it's a zip file) and replace the one in the dnSpy dir with the new file.

**Comment by xsilent007** [comment]
[This file should be the correct one](https://cdn.discordapp.com/attachments/599555556537008158/599555687978106881/CrackMe_KoiVm.exe)

**Comment by xsilent007** [comment]
I will test it ASAP

**Comment by xsilent007** [comment]
Yup, everything works correctly. Thanks!
