### ISSUE TITLE
Difference between dnSpy-netcore and dnSpy-net

### ISSUE THREAD

**Issue by iwanPlays** [0xd4d/dnSpy#1401]
What is the difference between:
dnSpy-net472.zip 22.4 MB
dnSpy-netcore-win32.zip 74.7 MB / dnSpy-netcore-win64.zip 81.1 MB

Clearly netcore is larger, so I assume that one should be used. ... because it has more libraries?

However I can't figure out what "Net" vs "Net Core" might be. Most comparisons are between "Net Framework" and "Net Core" and I would assume Net Framework is heavier because it has extra exclusive libraries?

Thank you!

**Comment by 0xd4d** [comment]
Most people have .NET framework 4.7.2 or later so the smaller *net472 file is probably better. If you don't have .NET Framework 4.7.2 or later installed, the .NET Core files can be downloaded instead since they contain the .NET Core runtime.

I've updated the release description:

dnSpy-net472.zip requires .NET Framework 4.7.2 or later.

dnSpy-netcore-win32.zip and dnSpy-netcore-win64.zip don't depend on .NET Framework, but use .NET Core instead which is included in the zip files.

**Comment by 0xd4d** [comment]
If you don't have .NET Framework 4.7.2 or later installed and try to run the *net472 file, you'll get a message box about downloading and installing it.
