### ISSUE TITLE
DNSPY is an amazing tool. I'm a novice, I don't understand C# but I have a very confusing problem

### ISSUE THREAD

**Issue by l100n** [0xd4d/dnSpy#1452]
![1](https://user-images.githubusercontent.com/56714143/80400991-302beb00-88ee-11ea-93d8-de4866872ef0.png)
![2](https://user-images.githubusercontent.com/56714143/80401001-33bf7200-88ee-11ea-9d31-8aebe5d680e8.png)

please let me explain in pictures

In the preview window of the main window, it displays
`public class SettingSorterOverlayVM : global::TaleWorlds.Library.ViewModel`

but when I select edit class
`public class SettingSorterOverlayVM : ViewModel`

But as a result, it will not compile

thx

**Comment by 0xd4d** [comment]
Did you try adding the namespace manually?

`public class SettingSorterOverlayVM : ViewModel` -> `public class SettingSorterOverlayVM : global::TaleWorlds.Library.ViewModel`

**Comment by l100n** [comment]
> 您是否尝试过手动添加名称空间？
> 
> `public class SettingSorterOverlayVM : ViewModel` -> `public class SettingSorterOverlayVM : global::TaleWorlds.Library.ViewModel`

yes,this solves the problem.but why does this happen?

**Comment by BlackFrog1** [comment]
Because it required the explicit namespace for the **ViewModel** object. You could be linking multiple library that all have an object call **ViewModel**.  When using a normally Visual Studio IDE we add using statements to the source code for brevity.  Basically [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar). When the source code is complied it references the full complete namespace object.
