### ISSUE TITLE
dnspy wont open 

### ISSUE THREAD

**Issue by paster44** [0xd4d/dnSpy#1493]
Dnspy wont open I downloaded the latest version in release and when I try to open it nothing happens I tried .net framework one and .net core I have c++ vc runtime installed and .net framework installed

**Comment by philipbawn** [comment]
Do you or your organization happen to have fireeye? It seems to be remediating mine by deleting dnSpy.dll

**Comment by 0xd4d** [comment]
Check if it's your anti-virus software. If it is, contact them.

**Comment by juliant99** [comment]
I am having the same issue and after some investigation dnSpy.dll is detected as a threat by 21 different engines as identified by VirusTotal. 
https://www.virustotal.com/gui/file/620f37703013af6d471d5f597f53a20a4eb95d8fa5b860fb7b39592ce80d6615/detection

**Comment by 0xd4d** [comment]
I suggest you contact your antivirus software. I checked 6.1.4 dnSpy.dll (.NET Core 64) and there were no detections.

**Comment by 0xd4d** [comment]
If I were a billion dollar company, they wouldn't dare do it, but hey it's open source so they don't care, just let some software give the verdict. At least Microsoft's antivirus seems to be well tested.

**Comment by Remo** [comment]
@0xd4d not really )-:

![image](https://user-images.githubusercontent.com/129864/86138941-656fd780-baef-11ea-9d96-00c526f69579.png)

**Comment by 0xd4d** [comment]
It was when I checked earlier today.

**Comment by 0xd4d** [comment]
@Remo why is your dnSpy in Program FIles? There's no installer. What's the hash of the file?

**Comment by Remo** [comment]
@0xd4d I extracted it there, no special reason.. I'm at a different computer, but I just downloaded this file earlier today https://github.com/0xd4d/dnSpy/releases/download/v6.1.5/dnSpy-netcore-win64.zip

**Comment by 0xd4d** [comment]
Anyone knows how to get more info from Microsoft about this?

**Comment by juliant99** [comment]
I am afraid I don't but it is either a false positive for whatever reason unknown, or your builds are genuinely infected by something. Is that possibility totally ruled out?

**Comment by 0xd4d** [comment]
They're compiled by GitHub Action and uploaded automatically from the CI to the releases page. I don't compile them myself.

https://github.com/0xd4d/dnSpy/runs/801401973?check_suite_focus=true

**Comment by Remo** [comment]
I guess we can submit the file here https://www.microsoft.com/wdsi/filesubmission

**Comment by 0xd4d** [comment]
You can do that. I suggest you contact your antivirus vendors and tell them to fix it. I have no control of their buggy algorithms.

**Comment by 0xd4d** [comment]
It's a false positive but I'm tired of these questions so the downloads have been removed. Compile yourself.

**Comment by 0xd4d** [comment]
BTW, https://github.com/0xd4d/dnSpy/actions has all CI builds.

**Comment by KinNeko-De** [comment]
Sorry for writing to a closed issue. I think i have some more information on why exactly dnspy does not open on windows machines

I discovered that the windows defender real time protection has a problem with the dnspy.dll. it will delete the dnspy.dll without any notification while unpacking the zip with the binaries. after that when you click on the dnsyp.exe a windows defender popup appears where you can execute the exe but nothing happens because the dnspy.dll was deleted.
you can switch off the real timeprotection but after switching on it deletes all dnspy.dlls.
check that the dnspy.dll is missing in the bin-folder.

The hint with "Compile yourself." really helps. i got it back to work compiling it with .net core sdk 3.1.
Thank you very much. DnSpy saved my life several times.

Ps.: The console application always worked.

**Comment by mubix** [comment]
This should be fixed ;) https://twitter.com/msdefenderatp/status/1281388571333558279?s=21
