### ISSUE TITLE
Releases are no longer accessable.

### ISSUE THREAD

**Issue by ril3y** [0xd4d/dnSpy#1525]
I just tried to download the latest release and there are only Unity debugging files being generated?  Did something change?

**Comment by hoshildharmendra** [comment]
I found them under the [actions tab](https://github.com/0xd4d/dnSpy/actions). Clicking on a commit shows the artifacts section with the relevant binaries.

**Comment by 0xd4d** [comment]
See the README or search the issues.

**Comment by poke** [comment]
I just had problems accessing the releases as well. Yes, they are available from within the Actions but apparently you can only access Action artifacts if you are logged into GitHub. This is somewhat a problem because I just had to log into my GitHub account on a remote machine just to download dnSpy. While I totally get why this was moved to Actions, this is somewhat suboptimal.

**Comment by ril3y** [comment]
@poke @hoshildharmendra I am logged into github.  I click on actions..  Click on the commit IE: https://github.com/0xd4d/dnSpy/commit/cc93bfc03958ca0a26901fe8073fe5c191019998 and then there are supposed to be Artifact files?  

I am a long time users of GH so I have no idea why this is not working?  Am I just missing something here?

**Comment by poke** [comment]
@ril3y From the [Actions page](https://github.com/0xd4d/dnSpy/actions) click on the latest successful action (or look for an action with a tagged version for more stability). Then, on the action detail page, it looks like this:

![Artifacts](https://user-images.githubusercontent.com/132240/87711294-5e132400-c7a7-11ea-999f-78a72d8279bd.png)

Those artifacts are clickable links—but only if you are logged in.
