### ISSUE TITLE
Feature Request：Breakpoint Directly from Analyzer

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#238]
![Breakpoint directly from the Analyzer?](http://i.imgur.com/8acccFb.png)

**Feature Idea:** It's good to be lazy sometimes, for example when you don't know where the heck something is happening and the only thing is a bunch of methods lying around in the Analyzer, and you'd wish to just put a breakpoint on them all, but you can't, this is why I have came up with the idea that could potentially be implemented for next release, maybe?

**Comment by SlowLogicBoy** [comment]
I imagine how I could implement this, however Debugger and Analyzer are on separate Extensions.

**Comment by 0xd4d** [comment]
I've been thinking about it myself, especially adding a breakpoint in every method of a class, let's call it a Class Breakpoint.

You don't need a reference to the analyzer since it already exposes the required info which you can find in the context passed to context menu handlers. Have a look at 'Search MSDN' or 'Copy MD Token' commands.

This feature should also support the Search window.

> For each selected item, try to find Method or Type, and if found add a BP to the method or all the type's methods. Don't add duplicate breakpoints.

**Comment by SlowLogicBoy** [comment]
> You don't need a reference to the analyzer since it already exposes the required info which you can find in the context passed to context menu handlers. Have a look at 'Search MSDN' or 'Copy MD Token' commands.

Thanks, I'll try to look into this.
