### ISSUE TITLE
Copy class or method ... as dnlib instructions

### ISSUE THREAD

**Issue by phonorepo** [0xd4d/dnSpy#294]
Dear Santa, ...

One thing that I would love to get would be the possibility to edit i.e. a method and then let dnSpy generate all instructions for dnlib that would be needed to recreate it with dnlib.

**Comment by 0xd4d** [comment]
I can see a use for this but the question though is if it's useful enough that it's worth writing the code?

Anyway, the easiest solution would probably be to create a new "language" that just outputs the C# code.

BTW, I think there's a .NET Reflector plugin that does something similar.

**Comment by phonorepo** [comment]
You're totally right, didn't know that there was such a plugin for Reflector, found it:
https://reflectoraddins.codeplex.com/wikipage?title=ReflectionEmitLanguage&referringTitle=Home
https://reflectoraddins.codeplex.com/SourceControl/latest#Source/ReflectionEmitLanguage/EmitLanguageWriter.cs

And it would totally help me right now where I write some kind of "Patcher" to add some functionalities to a program (and patcher to be able to patch all coming updated versions and don't have to manually go through everything again) that I think it shoul have, adding some controls here and there and writing this in csharp is easy but after that translating the il to dnlib with all references and espacially creating pointers with dnlib is at least for me not something that I can write out of my head ... but I bet you could do it.

**Comment by minexew** [comment]
I'm not sure I understand this correctly, but it seems relevant to my interests.

Is your goal basically to patch individual classes in an existing (proprietary/discontinued/...) .NET assembly?
Because I'm trying to do exactly that and I would be grateful for any hints about where to begin. I don't mind writing my own code, but as I have little experience with .NET, I don't really know what the most effective solution would be.

dnSpy has been a tremendous help in understanding the code, but now I'm looking for a way to modify it in an automatable way. The console tool doesn't seem to support modifying the original assembly in any way, am I correct?

**Comment by phonorepo** [comment]
"patch individual classes in an existing (proprietary/discontinued/...) .NET assembly?"
Yes exactly.

For smaller changes it is easy enough to write every dnlib-command by hand.
I did this for a lot of small changes.

For some of more complex changes I found it easier to copy existing IL and reuse it rather than manually to write down all the code.

But if we could "translate" csharp code or IL to dnlib within dnspy it would make it possible to write many lines of code in no time.

I think if you want to have full control you should try to create an own patching tool with dnlib.

Here are some examples:
https://github.com/0xd4d/dnlib/tree/master/Examples

And additionally you can have a look at my first tool where I used dnlib to insert code for tracing:
https://github.com/phonorepo/tracer/tree/master/pTracer_dnLib


> The console tool doesn't seem to support modifying the original assembly in any way
I havent tried the console but you can script dnspy, still I think it is better to use dnlib in an own application.
