### ISSUE TITLE
Can't see decompiled code

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#306]
![image](https://cloud.githubusercontent.com/assets/21169548/21151825/ff2e0932-c174-11e6-94ce-0571b6805d66.png)
It just have a comment about object name, and nothing more. Did I miss something? Is decompiling must be enabled separately? Using latest dnSpy from trunk.

**Comment by TiberiumPY** [comment]
Most strange thing ever.. It works with latest AppVeyor build

**Comment by 0xd4d** [comment]
It's because you haven't compiled everything. Compile everything (eg. press F6 is probably your keyboard shortcut for that command), do NOT press F5 unless you change a setting that builds every project when F5 is pressed.

Go to the help screen and you should see all extensions, in your build you should see no extensions since you built none.
