### ISSUE TITLE
Wrong color coding when root-namespace contains identically named class

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#339]
![](http://image.prntscr.com/image/458023a1c59e4c4faea22eb2b0ff377b.png)

Namespace: `Nuterra`
Class: `Nuterra`
Method: `Startup()`

But it thinks the `Nuterra` inside the method is the namespace, not the class. The coloring code should favor looking up classes over namespaces (like regular C#)

**Comment by 0xd4d** [comment]
It should colorize it according to what the compiler says it is, in this case, the compiler says that it can only be a namespace so it's colorized as a namespace. `Startup` is in red because the compiler couldn't find a symbol.

This is a decompiler bug, it should add a namespace to `Nuterra` so it's not confused with the namespace.

**Comment by maritaria** [comment]
What may be a usefull setting in these scenarios for most users would be the option to have all types fully written out, so you don't have any `using` statements. Then you always have a workaround available if such a bug arises again

**Comment by Albeoris** [comment]
A similar issue.

**There is two classes with the same name:**
MyNameSpace.Input
UnityEngine.Input

A recursive call as result:
```
		public static string[] GetJoystickNames() // MyNameSpace.Input
		{
			return Input.GetJoystickNames(); // MyNameSpace.Input
		}
```

**Comment by 0xd4d** [comment]
Decompiler bug.
