### ISSUE TITLE
The C# code editor

### ISSUE THREAD

**Issue by Rottweiler** [0xd4d/dnSpy#345]
I found some bugs/errors in the C# code editor
<hr/>
<h4>No. 1:</h4> 
If you edit the method signature of one method: Class.Method(byte[], string) to Class.Method() with the c# code editor, and then you try to insert a call to that method, it won't compile because it states the signature is wrong.<br/><br/><b>tl;dr</b>: the c# code editor won't recognize the method signature if you edit it
<hr/>
<h4>No. 2:</h4> 
The c# code editor won't know the class/method names if you edit them
<hr/>
<h4>No. 3:</h4> 
This bug in the c# code editor with labels (self-explanatory)
<img src="http://imgur.com/WlrAsSL.png">

**Comment by 0xd4d** [comment]
1. It doesn't support adding/removing parameters. That would break code calling the method since they expect N params, but after the change it's X params which isn't equal to N. If you really want to make this breaking change, right-click the method name and click `Edit Method` and click the `Signature` tab.

2. The code editor doesn't track renames. Workaround: right-click the method name or type name in the text viewer and click `Edit Method` or `Edit Type` and rename it.

3. Decompiled code isn't always 100% valid C#/VB code, sometimes you have to fix the bugs before pressing Compile.

**Comment by Rottweiler** [comment]
1. That's how I changed the signature, the editor didn't recognize the new parameters.
2. That's how I renamed it, again, the code editor didn't recognize this change
3. Yeah, I know, I just thought there was some way to fix this in the dnSpy code

Sorry for being unclear in the first post

**Comment by 0xd4d** [comment]
Have you tried saving the file (overwriting it)? If that doesn't solve it, could you list all the steps required to repro this?

**Comment by Rottweiler** [comment]
I didn't save it, I thought it was meant to refresh in memory
