### ISSUE TITLE
.NET Core debugger?

### ISSUE THREAD

**Issue by nictaylr** [0xd4d/dnSpy#353]
Are there any plans to add support for .NET Core `clrdbg`? This would become an increasingly useful feature as .NET Core gains traction for web and console apps.

**Comment by 0xd4d** [comment]
You can debug them on Windows, but I assume you would like to debug a .NET core application running on Linux / Mac? The current code can't do it, but it's something I might support in the future, but it's not a priority.

**Comment by nictaylr** [comment]
I tried on Windows with the latest SDK, but I'm getting an error with `dbgshm.dll`. I'm running an ASP.NET Core app after `dotnet publish -c Release` to a `.dll`. Perhaps you should update the dotnet file selection filter to include `*.dll` in addition to `exe` files, as .NET Core portable apps are DLLs run by the shared framework host `dotnet`.

**Comment by 0xd4d** [comment]
There's a 'Debug a CoreCLR assembly' dialog box but it requires some host, eg. CoreRun.exe if you have it. I quickly checked my .NET Core install dir and it didn't have that file anymore. It could've been renamed or some other could've been written that does something similar.

You could also debug it with dnSpy, pointing to the native file, and make sure your managed code calls Debug.Break(). For best debugging experience (that assembly will be optimized so you won't see most locals), that startup assembly should call the real assembly which will then be non-optimized once dnSpy is attached. You might try this (https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx) too, but I don't know if it works with .NET Core (could be a .NET Framework only thing)

Since you have the source code, why don't you use Visual Studio to debug it?

**Comment by nictaylr** [comment]
I'm testing out a complex obfuscator and want to ensure that certain components are working as intended.

**Comment by rfrfrf** [comment]
@nictaylr What is this 'complex obfuscator' called and how does it compare to other obfuscators?

**Comment by nictaylr** [comment]
it's different from anything i could find currently out there.
