### ISSUE TITLE
Unity+VB: Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#373]
When trying to compile a method I get "Multiple assemblies with equivalent identity have been imported" error.

It's because the target has an equavilent system dll inside its directory but DnSpy also loads all assemblies from GAC.

This error should/could be solved if I would be able to disable GAC references in DnSpy. Is there a way to do so?

**Comment by 0xd4d** [comment]
It could mean that you're editing a Unity assembly and you add refs to .NET Framework assemblies either directly or indirectly.

How do I repro this?

**Comment by Symbai** [comment]
Yep I was editing a unity assembly (Assembly-CSharp.dll). I have not added refs manually at all. Just dropped the assembly in DnSpy. Then tried to edit a method body and pressed compile.

You should be able to reproduce this if you have access to any Unity game where files like "mscorlib.dll" and "System.dll" are inside the "_managed" folder. If you don't have access I can probably upload something for you. You just need to tell me how you prefer me to upload and give it to you.

**Comment by 0xd4d** [comment]
You can email me the files and the repro steps to de4dot@gmail.com

**Comment by TiberiumPY** [comment]
@Symbai you can close ALL loaded assemblies, and then load Assembly-CSHarp.dll
also make sure you're using latest version from appveyor

**Comment by Symbai** [comment]
Downloaded 433  build from https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

File -> Close All
Drag & drop Assembly-csharp in Dnspy 64bit
Do the steps as shown in the video
Same problem.

Like written in the email the issue only happens when language in Dnspy is set to visual basic.

**Comment by TiberiumPY** [comment]
@Symbai don't set language to visual basic :)

**Comment by 0xd4d** [comment]
@Symbai I can repro it. It happens because you use Visual Basic and VB requires Microsoft.VisualBasic.dll to compile the code, so the VB-compiler code in dnSpy automatically adds that assembly reference if the language is VB. However, this assembly is for .NET Framework only, and you're editing a Unity assembly which I assume don't support VB (only C#).

**Comment by 0xd4d** [comment]
One can pass `embedVbCoreRuntime` == true when creating `VisualBasicCompilationOptions` without adding a VB.dll reference but there'll be some other error:

```
Error	BC31429	'Inherited' is ambiguous because multiple kinds of members with this name exist in class 'AttributeUsageAttribute'.		
```

This happens because dnSpy makes everything public so you can reference internal and private members. VB is case insensitive so will think field `xxx` is has the same name as property `XXX`. (Mono's mscorlib has property `Inherited` and backing store field `inherited`)

The only workaround at the moment is to use C#.
