### ISSUE TITLE
"Not showing all elements because this array is too big (23425 elements)"

### ISSUE THREAD

**Issue by erherhh4herh** [0xd4d/dnSpy#383]
I get this error when decompiling a class with a large array. How do I get the full array? Please help!

Thank you,
erherhh4herh.

**Comment by 0xd4d** [comment]
The full array isn't shown because it's not useful and will only cause OOM, see #87

Switch to IL code and you'll see something like:

```IL
		/* 0x00000265 D001000004   */ IL_0009: ldtoken   field valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=16' '<PrivateImplementationDetails>'::'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
		/* 0x0000026A 281000000A   */ IL_000E: call      void [mscorlib]System.Runtime.CompilerServices.RuntimeHelpers::InitializeArray(class [mscorlib]System.Array, valuetype [mscorlib]System.RuntimeFieldHandle)
```

Click on the field which in this case is called `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

```IL
	// Token: 0x04000001 RID: 1 RVA: 0x00002948 File Offset: 0x00000B48
	.field assembly static initonly valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=16' 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' at I_00002948 // 16 (0x0010) bytes
```

The comment says that it's `16 (0x0010) bytes` in size. You can click the RVA in the comment above to see the data in the hex editor where you can select the whole range and copy a C#/VB array.

**Comment by pravic** [comment]
Funny enough, this message appears even during export. 

I wonder, would it hurt to actually save that large array during export to source? I mean, in this case it won't be something that needs to be loaded in memory, drown in GUI and so on - just export (i.e. read chunk, save chunk).

**Comment by atom0s** [comment]
Also still seeing this error while exporting large arrays in a project. The resulting exported array will end with:
`Not showing all elements because this array is too big`
