### ISSUE TITLE
Missing Event Handlers

### ISSUE THREAD

**Issue by sksar** [0xd4d/dnSpy#385]
The subroutines in Visual Basic code are missing their respective event handlers.

The functions like click, doubleclick and all,  are missing handlers.

![image](https://cloud.githubusercontent.com/assets/11752260/23946856/2c1cbfae-09a2-11e7-85e6-0d2e497da64b.png)

As shown the subroutine which is selected (or highlighted) is missing its corresponding event handler...

**Comment by 0xd4d** [comment]
What code is missing? I see the click handler in the picture, so what should be present?

**Comment by SlowLogicBoy** [comment]
Dang I'm too late but I will add what he means:
In VB.net event handling happens like this:
`Public Sub CmdUpdate_Click(s As Object, e as EventArgs) Handles CmdUpdate.OnClick`
what is missing here is `Handles CmdUpdate.OnClick`

But since the main decompilation language is C#, so I think it is translated to VB.net just like in C#, so event wiring is happening like: `AddHandler CmdUpdate.OnClick, AddressOf Me.CmdUpdate_Click`
