### ISSUE TITLE
Replace the IL code of the method body with code

### ISSUE THREAD

**Issue by Alcatraz3222** [0xd4d/dnSpy#4]
Would be nice if it could be able to replace the method with code either all the method or just a line

**Comment by beppe9000** [comment]
up!

**Comment by BlueRaja** [comment]
This already exists as a ILSpy plugin: http://reflexil.net/

No idea if it will work for dnSpy as well.

**Comment by Klocko** [comment]
So, when will this be added? Right now I'm still using ILSpy with Reflexil because it has this feature.

**Comment by pyrostrex** [comment]
+1 on this, since I use it most of the time. :P.

**Comment by beppe9000** [comment]
+1 Altough I think it would be better with actual code editing like C# or VB instead of IL. Also reflexil has only limited support to code editing. I'd like a more java-like appoach where you create a project with tha exe as reference and the decompiled class, change it recompile and replace inside the executable...

**Comment by vpadlo** [comment]
Port of Reflexil plugin? [http://reflexil.net/](url)

**Comment by beppe9000** [comment]
I think it is better to implement it from scratch using Roslyn.

**Comment by SlowLogicBoy** [comment]
Is anyone working on this yet?

**Comment by galaris** [comment]
+1

**Comment by rolandh** [comment]
This would be super handy. Even if it simply compiles it to IL and you have to patch of manually.

**Comment by 0xd4d** [comment]
Try the beta version.

**Comment by vpadlo** [comment]
It's awesome! Thank you very much.
