### ISSUE TITLE
Generate PDB file?

### ISSUE THREAD

**Issue by salarcode** [0xd4d/dnSpy#418]
Is there a way to generate pdb files out of dlls?
If not this would be a helpful feature.
With PDBs it is easier to tackle down null reference errors.

**Comment by li0nsar3c00l** [comment]
When you click on Save Module, you can select Save PDB as well

**Comment by boodyman28** [comment]
when click save module Save PDB check button is disabled by default what is the problem here????

**Comment by salarcode** [comment]
Can't believe I didn't see that :-| , Anyway it is disabled for me too.

**Comment by 0xd4d** [comment]
That option only works when saving modified assemblies that already come with PDB files.

You can use a debugger to stop when there's a NRE.

**Comment by salarcode** [comment]
Right, but not always if the error happens in unknown/rare situations!
Being able to generate PDB from dlls would be really appreciated.

**Comment by 0x53A** [comment]
@0xd4d Are you working on this? Otherwise I will try to create an extension for dnSpy which does this.

I had a (more or less) working prototype for ILSpy some time ago https://github.com/0x53A/ILSpy/commit/fb70fe1a1e908448936f756ccf985579d94ff9b6, but never got around to push it out of poc state.

**Comment by 0xd4d** [comment]
No, I'm not working on this at the moment.

An extension could work, if it used the same decompilation options as "Export to Project".

A better (but perhaps a lot more work) fix is probably to update the "Export to Project" code (see https://github.com/0xd4d/dnSpy/tree/master/dnSpy/dnSpy.Decompiler/MSBuild ). Note that this code is multi threaded, but the PDB writer probably must be accessed from the same thread that created it.

**Comment by fireundubh** [comment]
@0x53A @0xd4d Have you looked at creating an extension for PDB generation yet? I was able to create a new PDB using dotPeek using this procedure:

1. Follow these instructions: https://github.com/0xd4d/dnSpy/wiki/Making-an-Image-Easier-to-Debug
2. Follow the "turning a release build into a debug build" instructions: https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games
3. When saving the module, in MD Writer Options, check Preserve All MD Tokens, Preserve Heap Offsets (all), Create Heap Even If Empty (all), and Misc Options (all except Keep Old MaxStack Value).
4. Compile these changes into de4dot: https://github.com/0xd4d/de4dot/pull/126/commits/28f33354c86cdbfc1d96134fab1132c87a99a5e3
5. Use de4dot with these flags: `--dont-rename --keep-types --preserve-tokens --preserve-strings -fpdb`
6. Use dnSpy to remove `DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints` from the assembly.
7. Use dotPeek to generate a PDB file. Wait a while for dotPeek to generate its DecompilerCache and write the PDB file.
8. For Unity games, run pdb2mdb through mono: `"D:\dev\Unity-2018.1.0f2\Editor\Data\MonoBleedingEdge\bin\mono.exe" "D:\dev\Unity-2018.1.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.5\pdb2mdb.exe" "E:\SteamLibrary\Pathfinder Kingmaker\Kingmaker_Data\Managed\Assembly-CSharp.dll"`
9. Replace `mono-2.0-bdwgc.dll` in the game's MonoBleedingEdge folder with the debug version.

Of course, dotPeek and dnSpy have different decompilation output, so the debug log line numbers are different. Since I prefer dnSpy's decompilation output (with Allow Field Initalizers off), it's much less useful to be using a dotPeek-generated PDB/MDB. It's also pretty annoying to have long paths to JetBrains' DecompilerCache in logs, like:

```
  at Kingmaker.UI.Group.GroupController.SetGroup () [0x0001a] in C:\Users\fireundubh\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\09F5CE65-F665-473C-AF7C-ED8E85B98B8B\18\021a9f57\GroupController.cs:190 
```

It'd be wonderful if dnSpy had native support or an extension for PDB generation.
