### ISSUE TITLE
When debugging, check if correct variant of dnSpy is used (x32/x64) before checking for administrator rights

### ISSUE THREAD

**Issue by ViRb3** [0xd4d/dnSpy#433]
Just a very minor improvement, feel free to neglect.

**Comment by 0xd4d** [comment]
Repro: dnSpy = x64 non-admin, target = x86 admin, message `"The debugged program requires admin privileges. Restart dnSpy with admin rights and try again."`

This happens because the CLR debugger returns error `0x800702E4` which is `The requested operation requires elevation.` The CLR debugger should return `0x80070032` or `0x80131C30` (`CORDBG_E_UNCOMPATIBLE_PLATFORMS` (sic))

**Comment by XenocodeRCE** [comment]
@0xd4d do you have a list where you can see which message is associated with an error ? (HRESULT or some sort of things)

**Comment by 0xd4d** [comment]
Visual Studio: Tools -> Error Lookup

CLR errors: https://github.com/dotnet/coreclr/blob/master/src/inc/corerror.xml
