### ISSUE TITLE
 C# guid must use uppercase in ProjectTypeGuids

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#475]
When I export wpf to project, the .csproj will contains:

`<ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>`

C# guid must use uppercase:
{fae04ec0-301f-11d3-bf4b-00c04f79efbc}=>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}

Otherwise, when adding new item to project, there's nothing in the installed template.

**Comment by 0xd4d** [comment]
Seems like VS is treating guids as case sensitive strings...

**Comment by CreateAndInject** [comment]
Yes, so you must follow it.

**Comment by 0xd4d** [comment]
Verified. :scream:

Marking up for grabs, it's an easy fix. If you or anyone else wants to fix it, search for the guid, make sure ToUpperInvariant() is called.

**Comment by tamlin-mike** [comment]
Since this smells like a VS bug (who in the right mind have heard of a hex value require uppercase-only A-F?), I'm going to file a bug @ roslyn and let them sort it out.
Since the probability of that getting fixed this side of 2020 is questionable, I regretfully have to agree dnSpy is forced to do this.
