### ISSUE TITLE
[question] dnSpy with Microsoft Assemblies

### ISSUE THREAD

**Issue by coltonmurphy77** [0xd4d/dnSpy#492]
Possibly stupid / dangerous question here. Has dnSpy been tested with the Microsoft .NET libraries by say decompiling one, then just resaving it and seeing if it works? 

My particular usage scenario is loading PresentationCore.dll, modifying a function marked internal to protected internal and just trying to save it back. 

When I create a new WPF project with the default template in VS2017, I get a squiggly under InitializeComponent in the MainWindow class. When I try to build, it gives me an error (paraphrasing):

Unknown build error: Could not load type (TYPE HERE) from assembly PresentationCore, ....... because the method (METHOD HERE) has no implementation (no RVA). Also has no .ctor (no RVA)

I fully understand that these are incredibly compilicated assemblies; however, I just would like to know if dnSpy would be able to modify such assemblies with 100% accuracy. Also, keep in mind, I get the error without any modification to said assembly. Opening the assembly in dnSpy then just doing a save produces a similar error when using the library.

I don't know the ins and outs of the save options dialog, but I have also tried various permutations with keeping offsets, MD, etc..

**Comment by 0xd4d** [comment]
It's a mixed mode assembly, try enabling that checkbox option.

How do I reproduce this?

**Comment by UlyssesWu** [comment]
I don't have much knowledge on this so maybe I'm writing something totally wrong.

If you are using the lib from path `Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7` (about 1331KB for PresentationCore.dll), it actually has many stub methods which have no implementation, resulting in the error you described.

There is a complete version is GAC `GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35` (3532KB). But VS / CLR? always try to load the dll from GAC rather than your modified version unless you removed the strong name. 

After strong name removed and by using Reflection you may get some results, but it seems useless...

![presentationcore](https://user-images.githubusercontent.com/4312781/29559276-3c3977e6-8761-11e7-9d5b-0a76a9166f46.png)

**Comment by LostTime77** [comment]
0xd4d:

To reproduce, decompile PresentationCore.dll in 
Program Files (x86)/ ReferenceAssemblies\Microsoft\Framework\.NETFramework\v4.6.1 using dnSpy, then just do a save all / save module and save the file to the desktop selecting various checkboxes in the save options. Then replace PresentationCore.dll in the framework folder with the modified version. My VS2017 references PresentationCore.dll in the framework folder when I create a new WPF app project. Nextly create a WPF app project in VS2017, default options & try to build. 

UlyssesWu:
I am fairly certain VS2017 is referencing my modified version and not the one in the GAC, because when I replace the original in the framework with the modified, VS2017 puts up a stink immediately on a new project. 
You may very well be correct with the strong names.. I don't know too much about it. I am going to try the mixed mode assembly option that 0x4d4 suggested.

**Comment by UlyssesWu** [comment]
As I have wrote, your errors come from the stub `PresentationCore` assembly, you won't get better result after enabling the option. You will find the difference by comparing with the GAC version.

> it actually has many stub methods which have no implementation, resulting in the error you described.

You are correct that VS will use the dll in `Reference Assemblies`, you can replace the incomplete one with the complete one in GAC, and modify the GAC version to avoid errors. But the fact is, when the program run, it still uses the GAC version. (And that GAC version has a native image generated by ngen)

**Comment by 0xd4d** [comment]
You're modifying a reference assembly, they're not meant to be executed, they usually don't contain any code at all.

**Comment by LostTime77** [comment]
Ok, I understand now. I am using the GAC version of PresentationCore. I can get the project to build and execute now by just doing a save operation after decompiling. 

Since, I am kind of new to this, I have a few additional questions:
1. The original GAC version of the file is 3.44MB and when resaved by dnSpy it spits out a file that is < 3.20MB. Why the difference in file size?

2. All I want to do is try to modify one of the internal methods of a class from internal void to protected internal void so it can be called by derived types. Once I do the modification, I can now use the method from derived classes; however, when run I get a method access exception when trying to execute the method. Do all assemblies referencing the modified assembly now have to be recompiled? Additionally, I  have also tried making the function public and still get the exception. The function does not have any security attributes for the method, but the assembly is definitely strongly named. I don't know what makes this modified method (now public) any different from functions originally marked public in the original assembly. 

Like I said, I am new to decompiling .NET assemblies, strong naming, security, etc.. and have been doing some research, so please pardon the ignorance.

**Comment by 0xd4d** [comment]
You can't just randomly change various things in the metadata and expect it to work. It's off topic, so suggested reading: the ECMA standard and anything about GAC you can find on the Internet.

**Comment by LostTime77** [comment]
I thought that was the point of dnSpy. Are you saying that the usage scenario is not to change method declarations but instead method bodies? I have also tried that too. I modified a string in the assembly for a public method, and that also failed to work. We are not talking gaping changes to the library here, the changes I have tried is literally a single word. 

Let's get away from the GAC. I have force loaded the modified assembly in a console app using Assembly.load. When I read the type information (MethodInfo) for the modified function (the protected keyword), the MethodInfo always has the original declaration flags specified and not the modified ones.

When I view the modified assembly with DotNet peek or dnSpy, the method is clearly decompiled with the the protected internal declaration I added to the function. For some reason, when this particular assembly is loaded, .NET doesn't want to use the modified declaration and reverts to the old one. 

I thought that dnSpy might have issues with modifying a strong named assembly, so I made my own strong named assembly with a dummy function marked internal and ran the same test by having dnSpy turn the method declaration to protected internal. When I used the dummy function, this surprisingly worked fine. 

At this point I don't believe this is off topic, because I have isolated the use case from the GAC by force loading the assembly and pulling the exported types out of it to discover that on the microsoft supplied assembly, dnSpy fails to work when doing a simple method declaration modification. This same test run on a strong name assembly that I generated works using dnSpy. DotNet peek and dnSpy both decompile the modified microsoft assembly and indicate that the method has been modified, yet when loaded it is not.

**Comment by 0xd4d** [comment]
As you say, dnSpy shows your changes, but the runtime doesn't use your modified assembly. Clearly this is a runtime issue. Google `fuslogvw.exe`

**Comment by LostTime77** [comment]
Complete victory! 

Using this tool I was able to figure out where and how exactly the assembly was being bound. The reason the modified method was not reflected was because the .NET runtime realized that the assembly had an native version in the GAC and was bypassing the modified version I was supplying. 

I went into the GAC and deleted the PresentationCore native image files and ran the log again and saw that it was using the modified assembly now. Calling the modified function from a derived class now works and does not throw a MethodAccessException.

Thanks!
