### ISSUE TITLE
variable/function/sub naming

### ISSUE THREAD

**Issue by mkaratha** [0xd4d/dnSpy#518]
Thanks for an incredible piece of software.
All compiler generated variables etc gets a "#" char prefix. 
Visual Basic B IDE (VS 2017) doesn't accept this character as an identifier. Is it possible to prevent/customize this prefix in dnSpy? The project is fairly large so just replacing this character with text editor will break several references/links.

Regards,
Michael from Sweden

**Comment by mkaratha** [comment]
I also noted that dnSpy can give different variables "same" name - only differ in text case. Eg "#1J" vs "#1j"
Since the IDE (at least VB IDE) is not case sensitive this makes it hard to clean up the exported project. It would be great to have access to a table of all "compiler named" variables that could be modified.

**Comment by UlyssesWu** [comment]
I'm afraid you are looking into an obfuscated assembly. Names like "#1J" are most likely renamed by an obfuscator rather than generated by the compiler. You can use [de4dot](https://github.com/0xd4d/de4dot) (another great tool by 0xd4d) to clean it.

Some compiler generated identifiers may contains characters like _<>_ which are not accepted as identifiers by the _C#_ compiler. Sometimes the decompiler handles them but sometimes not. Usually only at that time you'll have to rename them by yourself.

**Comment by mkaratha** [comment]
Thanks a lot for clear answer. I will try de4dot!

//Michael

**Comment by mkaratha** [comment]
Progress feedback:
First I descrambled the dll, using de4dot.exe. A new "cleaned" dll was generated. When I opened this new dll in dnSpy everything worked as expected!! Thanks!
