### ISSUE TITLE
Attach to process show an empty list

### ISSUE THREAD

**Issue by arkypita** [0xd4d/dnSpy#544]
First of all I want to thank you for this program.
I used it for the first time and allowed me to easily diagnose a deadlock of one of my application (i am a developer) on a customer's PC where I could not install visual studio. I use "attach to process", "break" then with "threads" and "call stack" windows i was able to find the locking-offending threads and synchronization objects.

Attracted by the goodness of the software and intrigued by wanting to try its features I install dnSpy also on my development machine. Unfortunately I'm having a strange behavior: the window "attach to process" does not show any process.

![image](https://user-images.githubusercontent.com/8782035/31394254-2f3c5a60-adde-11e7-87c4-34bee35c809f.png)

OS Win10, running under Administrator account, dnSpy x86 version. The sw I want to debug is a .net 2.0 x86 executable (the same application I have correctly debugged on customer PC).

**Comment by 0xd4d** [comment]
Is dnSpy run as administrator, it could be required if the program you would like to attach to is a protected process? The titlebar of dnSpy should include "Administrator" if it's run as administrator.

It's better to start the program instead of attaching to it, if possible. If you attach to it the JITter has optimized the code.

**Comment by arkypita** [comment]
Today everything it's working, with or without administrator right.
Nothing change except today test was done after a fresh boot of the PC.

If the problem re-appare i will do some more deep analysis
Best regards
