### ISSUE TITLE
InternalDebuggerError(TypeResolveException) with debugger's watcher if the name of exefile is changed(4.0.0beta1)

### ISSUE THREAD

**Issue by yyjdelete** [0xd4d/dnSpy#548]
Change the name of exefile to not match the name of module, and just watch any static/instance field or just `this`.

Seems dnspy failed to resolve the Assembly which is already loaded but has an different name in disk.

**Comment by 0xd4d** [comment]
The name is part of the metadata but dnSpy tries to avoid reading metadata if possible in case it's debugging something with 100s of files.

https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.Metadata/Impl/DmdAppDomainImpl.cs#L283

The fix: If it's an exe file it should always read the MD when resolving an assembly. This won't be a problem since 99% of all the files are DLL files.
