### ISSUE TITLE
dnSpy crashes on debug stop event

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#55]
version used:
dnSpy version 1.4.0.0 (release)

assembly under hands: mixed mode, .NET 1.1
Details:
Start debug session, press stop button.
Error:

http://prntscr.com/936v4p
when pressing Debug button:
VS2010 opens up,
high level info:
http://prntscr.com/936w2z
and here are the details on of the exception:
http://prntscr.com/936vsl
here is the stack trace that I hope will clarify the path:
http://prntscr.com/936sfk

this issue reproduced 100%.
Let me know if you need more details

**Comment by 0xd4d** [comment]
Looks like a crash in the CLR debugger where it's accessing invalid memory for some unknown reason. It's currently impossible for me to tell whether dnSpy is the cause of this until I can test the application.

You mentioned that it's a .NET 1.1 application. Is it using the .NET 1.1 runtime or is it the .NET 2.0-3.5 runtime? I've only tested the debugger with .NET 2.0-4.6 since I figured no-one uses 1.x anymore.

**Comment by greenozon** [comment]
You are right!
this must be a generic bug inside .NET 1.1!

when  I've added these lines into .config file of the app

  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0"/>
  </startup>

magically the dnSpy started to debug it like a charm!

thanks.
