### ISSUE TITLE
Is there something wrong with Local variable name between ver 3.X and 4.0?

### ISSUE THREAD

**Issue by yzpopulation** [0xd4d/dnSpy#573]
![](https://i.imgur.com/Txc3Gx4.png)

**Comment by HoLLy-HaCKeR** [comment]
The \uXXXX was the hexadecimal display of high Unicode characters that are not in the used font. It seems dnSpy 4.0 now tries to display the actual Unicode character, but it shows the box because it can't. The obfuscator used on the assembly you're analyzing did this, to make it harder to understand the code since you can't tell the difference between variables.

I think the 3.X representation was better. You should probably run your assembly through de4dot though, it should give everything more sensible names.

**Comment by yzpopulation** [comment]
@HoLLy-HaCKeR  Sometimes de4dot is not available, so I can only view it in dnspy.

**Comment by 0xd4d** [comment]
Yes it should be like in v3. It looks like the \uE01D is a local (it's not bold), but that shouldn't be possible, even in v4. The decompiler should've renamed it already.

**Comment by yzpopulation** [comment]
@0xd4d It still have some problem.
![Imgur](https://i.imgur.com/H1Q9Gq8.png)

**Comment by 0xd4d** [comment]
I mentioned the locals problem above but got no reply. Your first picture wasn't of much help, but this latest picture is better.

**Comment by 0xd4d** [comment]
@yzpopulation I can't reproduce it, upload the file here or email it to me.

**Comment by 0xd4d** [comment]
And make sure you're using the latest build from the build server, in case you're using a custom build.

**Comment by 0xd4d** [comment]
@yzpopulation  I forgot to mention it, but this was fixed, download the latest build.
