### ISSUE TITLE
dnSpy says when debugging "Exception: System.TypeInitializationException"

### ISSUE THREAD

**Issue by diamond94618** [0xd4d/dnSpy#608]
Before starting explain I wanna say I don't know correctly this is an issue of dnSpy or not.
Currently I am studying deobfuscation methods.
For now, I met an customized confuserex obfuscated file. I guess this protector is customized confuserex obfuscator from my experience.
But the debugging for anti-tamper removing can't be proceed from the 1st step.

My target exe file is detected by dnSpy like below

// Global type: <Module>
// Entry point: XXX.Program.Main
// Architecture: AnyCPU (64-bit preferred)
// Runtime: .NET Framework 4.5
// Timestamp: 59BA309B (2017-09-14 오전 7:32:43)

And when starting debuggging, then dnSpy popups dialog box like below

An unhandled exception occurred in XXX.exe (11576)
Exception: System.TypeInitializationException
"The type initializer for '<Module>' threw an exception."

So dubugging can't be started on first step. Without debugging it runs very successfully.
Is it disable to dubug my application with dnSpy? Is this the result of Anti-debugging method in the obfuscator?

**Comment by 0xd4d** [comment]
You should set a breakpoint @ `<Module>..cctor` because that's usually the entry point of the obfuscator's code. It's also possible that the entry point is some other `.cctor` method. If so you'll have to figure out which types `Main()` uses and check if those types have any `.cctor` methods.

**Comment by diamond94618** [comment]
When setting breakpoint on <Module>...cctor or not, the result are same everytime.
And I found new one thing. My target file always crashed when debugging on not only dnSpy but also Visual Studio and Ollydbg.
So I think my target file includes anti-debugging function.
How should I do for debugging it? Using dnSpy can't do it anymore?
Below is my target files uploaded URL, Main file is client.exe

https://www.dropbox.com/s/02ejw4y6gvjewqp/Program.7z?dl=0

**Comment by 0xd4d** [comment]
You're right, this is not a dnSpy issue, but I'll keep it open for a few more days in case someone else wants to have a look.

**Comment by HoLLy-HaCKeR** [comment]
I think I may have found the anti-debugger code that causes this. Note: all this happens in <Module>.

The obfuscator uses 3 different ways of detecting a debugger:

1. The classical `Debugger.IsAttached`,
2. `Debugger.IsLogging()`
3. A P/Invoke to `CheckRemoteDebuggerPresent` in kernel32.dll.

The results of 1 and 2 are stored in local `flag3`, and the result of 3 is stored in local `flag2` (assuming the given assembly). At around line 5727 (again, given assembly) if any of them are true, the switch int is set to 796373019u instead of 894877855u, which probably redirects control flow to some code that either calls a nonexistent type or corrupts a module that is being loaded.

I made a test program with the following code:
```cs
bool b1 = Debugger.IsAttached;
bool b2 = Debugger.IsLogging();
bool b3 = true;
CheckRemoteDebuggerPresent(Process.GetCurrentProcess().Handle, ref b3);

Console.WriteLine(b1);
Console.WriteLine(b2);
Console.WriteLine(b3);

Console.ReadLine();
```

Running it normally results in `false, false, false`. Running from Visual Studio or dnSpy with anti managed debugger detection disabled results in `false, false, false`. Running it in dnSpy with the anti debugger detection enabled, however, results in `false, false, true`.

So the problem is basically that `CheckRemoteDebuggerPresent` isn't "fixed" by dnSpy like `Debugger.IsAttached` and `Debugger.IsLogging()`.

**Comment by HoLLy-HaCKeR** [comment]
I'm not able to patch out the call and verify because dnlib is unable to write the file. de4dot also wasn't successful in producing a runable executable.

**Comment by 0xd4d** [comment]
'Prevent code from detecting a managed debugger' only disables `Debugger` class checks, not any OS (native) functions that detects debuggers. it's on my to do list though.

You can easily find the instruction with the help of dnSpy and use its hex editor to nop out any instruction. ;)
