### ISSUE TITLE
Is it impossible for correct decompilation about dynamic keyword and lambda expression using?

### ISSUE THREAD

**Issue by diamond94618** [0xd4d/dnSpy#621]
I am facing dynamic keywords and lambda expression using problem.
So I have searched on Google and found the explanation about the impossibility of their using by decompilers.
https://stackoverflow.com/questions/17988298/disassemble-net-c-sharp-library-with-dynamic-types
In here answer says like below.

Things that disassemblers cannot do:

recover comments in your original source code
recover const declarations in your original code
recover the name of local variables in your methods
cleanly decompile anonymous delegates
cleanly decompile iterators
cleanly decompile lambda expressions
cleanly decompile Linq query comprehensions
cleanly decompile code that uses dynamic variables.
cleanly decompile code that uses async/await

and in this article  said "You'll have to do it by hand, relying on your memory of what it might have looked like before."
Is it really?
Currently too many "o__SiteContainerXX" and "c__DisplayClassXXX" keywords are bordering me.
Of course I'm doing it one by one manually.

Can you give advantages in dnSpy for these correct decompilation similar with original code?

**Comment by HoLLy-HaCKeR** [comment]
```
cleanly decompile anonymous delegates
cleanly decompile iterators
cleanly decompile lambda expressions
cleanly decompile Linq query comprehensions
cleanly decompile code that uses dynamic variables.
cleanly decompile code that uses async/await
```
Decompilers attempt to recreate these as close as possible and do a pretty decent job at it right now, but your code is not compiled the exact way you write it. For example, a foreach loop will use an Enumerator, async will use some methods and lambda expressions generate classes.

Anyway, this is an ILSpy issue because they handle the decompiling, not dnSpy. Also, make sure that you have the correct dnSpy options enabled so it at least tries to generate the code: 

![img](https://i.imgur.com/OjKJqV9.png)

**Comment by diamond94618** [comment]
Thanks. I found it. 
Those checkboxes were already checked all. But there isn't any advantages with decompiling result.
