### ISSUE TITLE
dnspy unity steam game

### ISSUE THREAD

**Issue by maartenvd** [0xd4d/dnSpy#678]
Hi, I'm trying to debug a 64 bit unity game but (after replacing the mono.dll and making sure the game actually imports it) the debugger always fails to connect.
I've also tried to turn it in a debug build, but this just fails with "failed to load player settings".

How should I go about debugging this problem? Simply inspecting code is no problem and works like a charm.

**Comment by 0xd4d** [comment]
Use latest dnSpy build, latest built mono.dll files, make sure you're using the correct version, make sure you're using x86 or x64 mono.dll file, make sure you replaced the correct file (delete it, start the game, it should fail, restore it, start the game, it should work)

**Comment by LAntorcha** [comment]
What happens if the game is 32-bit and your system is 64-bit? Cause i have same issue. Downloaded both versions, it runs with x64 mono.dll but dnSpy refuses Attaching Debugger. Tried both versions of dnSpy.exe

If I make the opposite game won't load (sends mono.dll error).

**Comment by maartenvd** [comment]
Yeah, this also never worked for me, I just gave up.

2018-03-30 11:07 GMT+02:00 LAntorcha <notifications@github.com>:

**Comment by 0xd4d** [comment]
Only the game's bitness (32-bit vs 64-bit) matters. If the game is 32-bit, use the 32-bit (x86) files, if it's 64-bit use the 64-bit (x64) files.

You can't attach it using the .NET Framework attach to process dialog box.

The Unity attach to process dialog box only works with debug builds. Unless you built the game yourself or read the wiki and converted it to a debug build, you shouldn't use this dialog box.

Terminate the game, make a backup copy of its mono.dll, overwrite it with the correct version as explained in the wiki, start the game, then in dnSpy: Debug -> Start Debugging -> Debug Engine -> Unity (Connect) and press OK. It assumes the game is listening on port 55555 which is the default port if you used dnSpy's patched mono.dll.

**Comment by 0xd4d** [comment]
If the game is 64-bit, use 64-bit dnSpy (dnSpy.exe)

**Comment by 0xd4d** [comment]
Also get the latest build of dnSpy. You could be using an old version. https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by LAntorcha** [comment]
![development build tag](https://user-images.githubusercontent.com/37927331/38159776-d8e7e19e-34af-11e8-8044-96b77416b7f5.jpg)

I think i've done it well by the image (that tag wasn't there earlier). Downloaded the right Unity build? I got the x64 Unity cause my Pc is x64...
But the game.exe is 32-bit. Should i install Unity (5.4.4f1) 32?

I'm going to have both Unity 5.4.4f1 builds (x32 and x64 versions) installed in two different folders. And gonna repeat the whole process again.
First i would try the x32-All setup, then x64-All setup, and compare results.

**Comment by LAntorcha** [comment]
![unity connect](https://user-images.githubusercontent.com/37927331/38160221-488d5f24-34ba-11e8-933e-c6f666929f71.jpg)

I put 55555 and the IP field blank. Is this correct?

**Comment by 0xd4d** [comment]
You have a dev build, so you should use the Unity attach to process dialog box.

**Comment by 0xd4d** [comment]
Also make sure your firewall doesn't block dnSpy. If you use the patched mono.dll, it needs to connect to 127.0.0.1:<port> and if you try to attach to a dev build, it must use some multicast IP addresses to discover it.

Trying to figure out why it won't work for you using github issues will probably take weeks.

Step by step guide with some freeware game I used when testing the debugger:

Link: https://oultrox.itch.io/cubito

Click download, click "No thanks, just take me to the downloads", and download "Cubito - Desktop Version (v1.3)"

Check file props of `Cubito.exe`, it's v5.6.2.

Drag the exe to dnSpy, open PE node, and you'll see it's 32-bit ("Optional Header (32-bit)")

Go to https://github.com/0xd4d/dnSpy/releases and download `Unity-debugging-win32.zip` since it's for 32-bit Unity 5.x or later, and unzip it somewhere.

Since it's 5.6.2, copy `Unity-debugging\unity-5.6.2\win32\mono.dll` to `Cubito - Version 1.3\Cubito_Data\Mono`, overwriting its mono.dll file

This is a game that you can start just from dnSpy since it doesn't require Steam starting it etc so you could drag Cubito.exe to dnSpy and press F5 and ENTER. But I'll show how to attach to it after it's already started:

Start the game (Cubito.exe).

Start dnSpy (I used 32-bit, but 64-bit should also work with Unity games)

Debug -> Start Debugging -> Debug Engine -> Unity (Connect) -> hit OK

Now you'll notice that nothing happens. Some games stop completely when they don't have keyboard focus. Click the game window so it gets focus. dnSpy's module window should now show 8 loaded modules.

**Comment by 0xd4d** [comment]
Also when debugging Unity games, unless you have a multi-monitory system, always debug the game when it's in its own window, and not full screen.

**Comment by LAntorcha** [comment]
I _made_ a Dev Build following your instructions... and it doesn't show.

Surprisingly, if i rename the mono.dll in the meantime it appears in the Process search engine. ?¿?
