### ISSUE TITLE
Mixed-mode DLLs are enlarged when saved

### ISSUE THREAD

**Issue by catester** [0xd4d/dnSpy#83]
For example, if you edit a 20 MB mixed-mode DLL, you can get a 22 MB DLL after saving. Also if you re-open and edit the new DLL, it's enlarged again (e.g. 24 MB) when you save so it's incremental. Do you have any idea why this happens? I noticed the extra bytes are added at the end of the file, not sure if these are junk data or if they are really required.

**Comment by 0xd4d** [comment]
The original file is used and a new section with the new .NET metadata is appended because it's not easy to find every reference to native data, code and correctly find their lengths. It could be possible to re-use the original metadata location if the new MD fits in the old location etc, but it's an optimization that's far down on my to do list since there are so few mixed mode assemblies available.

**Comment by catester** [comment]
Ok I understand now. The reason I asked is that dnSpy is currently the only tool that can edit mixed-mode assemblies (Simple Assembly Explorer can not do this). So for now I try to do the changes at one go and save once to prevent incremental enlargement.

**Comment by 0xd4d** [comment]
You can save multiple times as long as you don't try to re-open the saved file and modify it and then save it. The opened file doesn't contain the extra section, only the saved file does.
