### ISSUE TITLE
Pls add support net framework 1

### ISSUE THREAD

**Issue by ahvahsky2008** [0xd4d/dnSpy#874]
Thx

**Comment by 0xd4d** [comment]
It can already decompile .NET 1.x assemblies.

It can't debug them with CLR 1.x since the CorDebug 1.x API was buggy.

The assembly resolver perhaps doesn't search for .NET 1.x assembliess in the right locations, but you can drag them to Assembly Explorer if needed.

I see no reason to fix this since .NET 1.x is dead.

**Comment by CreateAndInject** [comment]
ILSpy has supported .net 1.x resources without loading assembly, will dnspy merge related code from ILSpy?

**Comment by 0xd4d** [comment]
When MS brings back .NET 1.x from the dead.
