### ISSUE TITLE
Find where an enum item is being used

### ISSUE THREAD

**Issue by StackDoubleFlow** [0xd4d/dnSpy#888]
Same as #337 
I'm trying to see where a specific item in an enum is being used but I don't think it's a feature.

**Comment by 0xd4d** [comment]
Enum values are just integers in the IL code so the analyzer, which just scans the raw metadata, doesn't know that some integer is actually MyEnum.X instead of 3. I don't plan on implementing it and don't expect anyone else to do it so you'll have to settle for a workaround:

File -> Export to Project and open the solution in VS and use its Find All References feature.
