### ISSUE TITLE
Duplicate members if their sigs have modopt/modreq

### ISSUE THREAD

**Issue by ToBeTested** [0xd4d/dnSpy#939]
- What version did you use?
v5.0.7 (x64)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Working on obfuscated assembly. I am trying to edit methods body by the "Edit Method (C#)..." option.
On the first try (fresh, untouched *.dll) I am able to edit single method - solve the only compilation error (CS1519) by removing the WinForm deconstructor from main.g.cs, compile it and save. Then checking the code in dotPeek - changes are present. 
Therefore doing it second time, there are additional compilation errors (just duplicated entries in main.g.cs). Deleting it (and pressing compile afterwards) works without any errors (at least visible), but then after saving - the changes are not applied to the assembly itself - checking the file in dotPeek showing no diffs from previous version

![2018-09-15](https://user-images.githubusercontent.com/43297260/45587424-84df4580-b905-11e8-9577-602023ffa295.png)

[ObfuscatedAssembly.zip](https://github.com/0xd4d/dnSpy/files/2385799/ObfuscatedAssembly.zip)

**Comment by UlyssesWu** [comment]
When you use "Edit Method" on a method, you shouldn't edit other methods (except removing them) since the modifcation won't apply. If you want to edit another method, just use "Edit Method" on that, or try "Edit Class".

**Comment by ToBeTested** [comment]
Could you point out where's the mistake I'm doing? 
Cause I'm really not sure where (if at all) I'm editing other methods. 
As mentioned - the first try succeeding - it's compiled, saved, checked in another programm to verify.
And then modifying another method in completly separate session - reloaded files, used "Edit Method" context option once again.

**Comment by UlyssesWu** [comment]
When you save the module for the second time, are you overwriting an existing file (since this might lead to a failure and your file is not saved actually) ? Try close all assemblies in dnSpy, open the assembly you want to edit, edit the method, and then save to another location.

**Comment by ToBeTested** [comment]
Thanks for answer. Made sure to always save as a new file. Still don't working. I'll try it later on another machine to check if there's something wrong with my config.

**Comment by 0xd4d** [comment]
This happens because the C++/.NET compiler adds modopt/modreq to some of the method/field signatures. The decompiler doesn't know how to translate that to C# code, and of course the C# compiler then creates the new signatures without the modopt/modreq parts. dnSpy thinks new fields/methods have been added and adds them to the code.

Workaround: delete the new ones (move to the member, press delete). Which ones are new? Compare the tokens, the one with the smallest token is the original method/field. Make sure the edited method doesn't use the removed field or calls the new method. If so you have to open the IL editor and fix it before deleting the member.

dnSpy should be smarter and if the original member has modopt/modreq and it can't find it, it should try to find the member without any modopt/modreq, and if found, assume it's the same member.

**Comment by 0xd4d** [comment]
Another workaround is to remove as much as possible from main.g.cs

**Comment by ToBeTested** [comment]
Thank you very much. 
Went for option 2 straight away and it worked for me.

**Comment by 0xd4d** [comment]
I plan on fixing this so I'll reopen it.
